format = """\
  $username\
  $localip\
  $directory\
  $package\
  $git_branch\
  $git_commit\
  $git_state\
  $git_status\
  $fill\
  $cmd_duration \
  $c\
  $elixir\
  $elm\
  $golang\
  $gradle\
  $haskell\
  $java\
  $julia\
  $nodejs\
  $nim\
  $rust\
  $scala\
  $memory_usage \
  $line_break\
  $jobs\
  $character\
  """

right_format = """\
  -

  $status \
  $time\
  """


[username]
format = "[$user]($style) "
style_user = "bold #8be9fd"
show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
truncation_symbol = "repo: "
read_only = " "

[package]
symbol = " "

[git_branch]
style = 'italic purple'
symbol = " "

[git_commit]
style = "bold white"
tag_symbol = "笠 "
tag_disabled = false

[git_status]
conflicted = "= "
ahead = "⇡×${count} "
behind = "⇣×${count} "
diverged = "${ahead_count}×⇕×${behind_count} "
untracked = "?×${count} "
stashed = "\\$×${count} "
modified = "!×${count} "
staged = "+×${count} "
renamed = "»×${count} "
deleted = "✘×${count} "

[fill]
symbol = "-"

[cmd_duration]
format = " took [$duration]($style)"
show_notifications = true
min_time_to_notify = 60_000

[env_var.WSL_DISTRO_NAME]
format = " [$env_value]($style)"
style = "underline purple"

[env_var.MSYSTEM]
format = " [$env_value]($style)"
style = "underline purple"

[shell]
format = " \\[[$indicator]($style)\\] at"
powershell_indicator = "pwsh"
style = "bold blue"
disabled = false

[battery]
full_symbol = "•"
discharging_symbol = ""
charging_symbol = ""
unknown_symbol = "!"
format = " [$symbol$percentage]($style)"

[[battery.display]]
threshold = 20
style = "italic red"

[[battery.display]]
threshold = 80
style = "italic green"

[[battery.display]]
threshold = 100
style = "italic yellow"

[time]
disabled = false
format = " [$time]($style)"
style = "italic cyan"

[status]
disabled = false
format = "[$symbol$status]($style)"
symbol = "✕ "

[memory_usage]
format = " [${ram}]($style)"
threshold = -1
disabled = false

[aws]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "
format = '[ $symbol $context ]($style) $path'

[golang]
symbol = " "

[java]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[swift]
symbol = "ﯣ "

[os]
format = "[($name )]($style)"
style = "fg:#8be9fd"
disabled = false  # Disaled by default

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[localip]
disabled = false
format = '[\[$localipv4\]]($style) '
style = 'bold blue'
ssh_only = false
